name: Update GitHub Profile Metrics

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "README.md"
      - ".github/workflows/metrics.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: noxYJZeng
          template: classic
          filename: metrics.svg

          base: header, activity, community
          config_timezone: America/New_York

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size
          plugin_languages_limit: 8
          plugin_languages_indepth: no
          plugin_languages_analysis_timeout: 15

          # LeetCode stats
          plugin_leetcode: yes
          plugin_leetcode_user: nasirellazeng
          plugin_leetcode_sections: solved


